name: Clear Cloudfront Cache

on:
  workflow_call:
    inputs:
      role_to_assume:
        required: true
        type: string
      distribution_id:
        required: true
        type: string

# These permissions are needed to interact with GitHub's OIDC Token endpoint.
permissions:
  id-token: write   # This is required for requesting the JWT

jobs:
  clear-cache:
    name: Clear Cache
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.role_to_assume }}
          aws-region: us-east-1

      - name: Clear Cloudfront Cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ inputs.distribution_id }} \
            --paths "/*"
