name: Build and Deploy to Production

on:
  push:
    branches: [production]
  workflow_call:

# These permissions are needed to interact with GitHub's OIDC Token endpoint.
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

concurrency: deploy_production

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yaml
    with:
      role_to_assume: arn:aws:iam::268122344015:role/system/viget-startups-production-github
      bucket_name: viget-startups-production

  clear-cache:
    needs: deploy
    uses: ./.github/workflows/clear-cloudfront.yaml
    with:
      role_to_assume: arn:aws:iam::268122344015:role/system/viget-startups-production-github
      distribution_id: E3F4KGIY1FPQGV
