name: Refresh Production

on: workflow_dispatch

concurrency: refresh_production

jobs:
  empty-bucket:
    if: github.ref == 'refs/heads/production'
    uses: ./.github/workflows/empty-s3.yaml
    with:
      role_to_assume: arn:aws:iam::268122344015:role/system/viget-startups-production-github
      bucket_name: viget-startups-production

  deploy:
    needs: empty-bucket
    if: github.ref == 'refs/heads/production'
    uses: ./.github/workflows/deploy-production.yaml
